import spacy


def clean_structure ( string ):

	print ( ' >> string:', string )

master_list  = [
	'Strong communication skills. You must be able...',
	'Strong product sense. You must be able...',
	'Learning mentality. You must be able...',
	'Job Duties : Formulate, implement...',
	'Minimum Requirements : Master’s degree...',
	'Special Skill Requirements : (1) Java; (2) C++; (3) C...',
	'Salary : $156,030.00 - $168,700.00 per ann...',
	'Strong communication skills. You must be able to work with cross-functional partners to gather requirements and explain outcomes...',
	'Strong product sense. You must be able to align your work with business objectives and make appropriate tradeoffs...',
	'Learning mentality. You must be able to pick up new skills as needed and demonstrate a curiosity about new technologies...',
	'Title::Software Engineer...',
	'Job Summary\nPlay a part...',
	'Description\nYou will be...',
	'Education\nB.S. or M.S. in Computer Science or related field...',
	'Job Type: Contract...',
	'Pay: $70.00 - $78.00 per hour...',
	'Work Location: In person...',
	'Job Title: Embedded Software Engineer...',
	'Job Location: Redmond, WA...',
	'Job Type: 12 Months Contract...',
	'Job Type: Contract...',
	'Pay: $108.00 - $113.00 per hour...',
	'Work Location: In person...',
	'Why Join Us\nAt TikTok...',
	'Team Introduction\nEnterprise Solution RD...',
	'Job Information\nThe base salary range...',
	'Who we are\nAt Marketo ( an Adobe company ) we...',
	'The Opportunity\nAre you ready...',
	'Job Category Software Engineering...',
	'Job Duties : Design and implement...',
	'Minimum Requirements : Master’s degree...',
	'Special Skill Requirements : (1) Java (2 years); (2) REST...'
]

headers_list = [
	'Strong communication skills. ',
	'Strong product sense. ',
	'Learning mentality. ',
	'Job Duties : ',
	'Minimum Requirements : ',
	'Special Skill Requirements : ',
	'Salary : ',
	'Strong communication skills. ',
	'Strong product sense. ',
	'Learning mentality. ',
	'Title::Xxx',
	'Job Summary\n ',
	'Description\n ',
	'Education\n ',
	'Job Type: ',
	'Pay: ',
	'Work Location: ',
	'Job Title: ',
	'Job Location: ',
	'Job Type: ',
	'Job Type: ',
	'Pay: ',
	'Work Location: ',
	'Why Join Us\n ',
	'Team Introduction\n ',
	'Job Information\n ',
	'Who we are\n ',
	'The Opportunity\n ',
	'Job Category Software Engineering...',
	'Job Duties : ',
	'Minimum Requirements : ',
	'Special Skill Requirements : '
]

clean_list = [
	'Strong communication skills',
	'Strong product sense',
	'Learning mentality',
	'Job Duties',
	'Minimum Requirements',
	'Special Skill Requirements',
	'Salary',
	'Strong communication skills',
	'Strong product sense',
	'Learning mentality',
	'Title',
	'Job Summary',
	'Description',
	'Education',
	'Job Type',
	'Pay',
	'Work Location',
	'Job Title',
	'Job Location',
	'Job Type',
	'Job Type',
	'Pay',
	'Work Location',
	'Why Join Us',
	'Team Introduction',
	'Job Information',
	'Who we are',
	'The Opportunity',
	'Job Category Software Engineering',
	'Job Duties',
	'Minimum Requirements',
	'Special Skill Requirements'
]
